### ISSUE TITLE
Add folder

### ISSUE THREAD

**Issue by slimline33** [n8henrie/eyeflask#2]
It is possible to ad a folder for each date of the file?

/%dd-%mm-%yy

I use it as an alternative software for EyeFi Uploading Center... :)

**Comment by n8henrie** [comment]
Yes, this seems possible to add. I don't have time at the moment but will add to a list of features.

If somebody wants to contribute a PR, I'd ideally like to see this implemented as a config variable, where one could set it to some strftime string that would provide the folder structure and/or filename. If left empty it would continue to have the current behavior.
